import {Inter} from "next/font/google";
import "./globals.css";
import "./prism.css";
import { ClerkProvider } from "@clerk/nextjs";
import { AppContextProvider } from "@/context/AppContext";
import { Toaster} from "react-hot-toast";

const inter = Inter({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  fallback: ['system-ui', 'sans-serif'],
})


export const metadata = {
  title: "Aarogya",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider >
      <AppContextProvider>
    <html lang="en">
      <body
        className={`${inter.className}   antialiased`}
      >
        <Toaster toastOptions={
          { success: { theme: { primary: "#4ade80" } } ,
            error: { theme: { primary: "#f87171" } } 
          }}/>
        {children}
      </body>
    </html>
    </AppContextProvider>
    </ClerkProvider>
  );
}
